FROM node:20-alpine as base

# ;-------------;
# ; Build stage ;
# ;-------------;
FROM base as builder

WORKDIR /app

RUN npm i -g pnpm

COPY . .

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
    pnpm install --frozen-lockfile && \
    pnpm --filter server build && \
    pnpm prune --prod

# ;---------------;
# ; Runtime stage ;
# ;---------------;
FROM base as runtime

WORKDIR /app

COPY --from=builder /app/ ./

CMD ["node", "apps/server/dist/main.js"]
