name: Build and deploy server to Azure Web App

on:
  push:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  purge-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Build server
        run: |
          pnpm install
          pnpm server:build

      - name: Zip dist files for upload between jobs
        run: cd ./apps/server/dist && zip --symlinks -r xsighub.zip *

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: xsighub-server
          path: ./apps/server/dist/xsighub.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: xsighub-server

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'xsighub'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F72962858F07443F9FBA6688EA84DCF4 }}
          package: xsighub.zip

      - name: Delete zip file
        run: rm xsighub.zip
